language: r
sudo: false
warnings_are_errors: false
dist: trusty
r: devel
cache: packages

latex: true
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'

r_github_packages:
  - jimhester/covr

env:
  matrix:
    - CVV_OLEVEL=2 CXX=clang++

script:
  - |
    travis_wait R CMD build .
    travis_wait 42 R CMD check growmod*tar.gz

after_script:
  - tar -ztvf growmod_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat growmod.Rcheck/00install.out

