la4-48b7-ba98-64669c7bfd48anguage: r
sudo: required
warnings_are_errors: false
r: devel
cache: packages
dist: trusty

latex: true
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples --install-args="--preclean"'

r_github_packages:
  - jimhester/covr

env:
  global:
    - CRAN: http://cran.rstudio.com
  matrix:
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ; then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

script:
  - |
    travis_wait R CMD build .
    travis_wait 42 R CMD check growmodr*tar.gz

after_script:
  - tar -ztvf growmodr_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - tar -C .. -xf $growmodr_*.tar.gz
  - travis_wait 40 Rscript -e .codecov.R 

after_failure:
  - cat growmodr.Rcheck/00install.out

